((lambda (x y z) x) 1 2 3)
((lambda (x y z) y) 1 2 3)
((lambda (x y z) z) 1 2 3)
((lambda (x) "he works") 1)
((lambda (x z) z) 1 2)
((lambda (x y z e f g) z) 1 2 3 4 5 6)
((lambda (x) x) "asdka la")
((lambda () #\z))
((lambda (x) 3) 3)
((lambda (x) 3) 1)
((lambda (x) 12) 3)
(lambda () 1)
((lambda () 1))
(lambda () (lambda () 1))
((lambda () (lambda () 1)))
(define id (lambda (x) x))
(id "id:")
id
(id id)
((id id) id)
;(define ind (lambda (x) ((lambda (x) x) x)))
;(ind "ind:")
;ind
;(ind ind)
;((ind ind) ind)
;(((ind ind) (ind ind)) ind)
;(ind id)
;(id ind)
