(boolean? #f)
(boolean? #t)
(boolean? 3)
(integer? 1)
(integer? 0)
(pair? '(1 2 3))
(pair? '())
(pair? 1)
(car '(1 2))
(cdr '(1 2))
(car '(2))
(cdr '(2))
(cons 1 2)
(car (cons 1 2))
(cdr (cons 1 2))
(let ((x (cons 1 2))) (set-cdr! x 3) x)
(string-length "asdnlsdkfj")
(string-length "124d")
(string-length "")

